JBOSS_BIND_ADDRESS=${JBOSS_BIND_ADDRESS-localhost}
echo JBOSS_BIND_ADDRESS=$JBOSS_BIND_ADDRESS
curl -s http://$JBOSS_BIND_ADDRESS:$JBOSS_HTTP_PORT/jmsclient-0.0.1-SNAPSHOT/ClientServlet | grep "Message sent"
